server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

ingester:
  trace_idle_period: 10s
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces

query_frontend:
  search: {}


metrics_generator:
  processor:
    span_metrics:
      dimensions: ["http.method", "http.status_code"]
